# Generated by Django 3.1.3 on 2021-04-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films_of_shopifolx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='imdb_ID',
        ),
    ]
