# Generated by Django 3.1.3 on 2021-04-28 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films_of_shopifolx', '0002_remove_film_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imdb_id',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_of_shopifolx.film')),
            ],
        ),
    ]
